name: Main
on: [push]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Build
        run: |
          pnpm install
          pnpm run build
          pnpm exec playwright install
      - name: Run tests
        run: pnpm run test
      - uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    # if: github.ref == 'refs/heads/deploy'
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - run: npm publish --dry-run --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
